spring.application.name=teampulse
server.port=3333

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/teampulse
spring.datasource.username=root
spring.datasource.password=ptr3

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true